### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by rowoot** [rowoot/gulp-gh-pages#50]
Hi folks,

Thanks for providing inputs / PRs to this project. The project currently does ~100 npm downloads a day. More stats available here: https://www.npmjs.com/package/gulp-gh-pages. It is clear that there are a lot of you folks building great software and want a way to publish to gh-pages in an easy manner -- gulp-gh-pages definitely attempts to solve this problem.

However, I am caught up with other projects and thus unable to provide time to maintain gulp-gh-pages, I am looking out for maintainers who will be willing to take over this project and provide the love it really deserves.

Thanks,
Micheal

**Comment by shinnn** [comment]
:hand:  I can take it on.

I'm maintaining some gulp plugins whose owners are too busy to maintain them:

* adamayres/gulp-wrap#16
* adametry/gulp-eslint#24
* lmtm/gulp-front-matter#5

**Comment by rowoot** [comment]
Awesome, thanks @shinnn. 
@MoOx, would love to hear your thoughts (if any) given your contributions to this project.

**Comment by shinnn** [comment]
And this :)

* kombucha/gulp-assets#8

**Comment by rowoot** [comment]
hey @shinnn, sorry was OOT, Are you still up for maintaining gulp-gh-pages? Let me know how I can transfer ownership of the project. Thanks!

**Comment by shinnn** [comment]
> Are you still up for maintaining gulp-gh-pages? 

Of course!

> Let me know how I can transfer ownership of the project.

This doc helps us. https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

Specify `shinnn` (triple `n`) as a new owner.

**Comment by shinnn** [comment]
And, please give me owner access to [the npm package](https://www.npmjs.com/package/gulp-gh-pages).

This command will do the trick.

```sh
npm owner add shinnn gulp-gh-pages
```

**Comment by rowoot** [comment]
Added shinnn as owner to gulp-gh-pages
```
➜  ~  npm owner add shinnn gulp-gh-pages
+ shinnn (gulp-gh-pages)
```

**Comment by rowoot** [comment]
I am unable to transfer repo since `shinnn/gulp-gh-pages already exists`. Could you go ahead and delete it so I can transfer it. Also, I would like to request collaborator access for myself and @MoOx once the transfer is complete -- sound good?

**Comment by shinnn** [comment]
Oh, sorry. Now I deleted shinnn/gulp-gh-pages.

> I would like to request collaborator access for myself and @MoOx once the transfer is complete

Sure thing.

**Comment by rowoot** [comment]
Done, transfer is in progress. Thanks a ton @shinnn.

**Comment by shinnn** [comment]
:+1: I've recieved the repo. Thanks, @rowoot.
